version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data


  backend:
    container_name: backend
    image: backend:latest
    build: ./backend
    env_file:
      - ./backend/.env.sample
    ports:
      - "5000:5000"        
    depends_on:
      - mongodb
    volumes:
      - ./backend/.env.sample:/.env.sample

  frontend:
    container_name: frontend
    image: frontend:latest
    build: ./frontend
    env_file:
      - ./frontend/.env.sample
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/.env.sample:/.env.sample
volumes:
  data:
  .env.sample:
